export const UPLOAD_TEACHER_PHOTO_REQUEST = 'UPLOAD_TEACHER_PHOTO_REQUEST ';
export const UPLOAD_TEACHER_PHOTO_SUCCESS = 'UPLOAD_TEACHER_PHOTO_SUCCESS';
export const UPLOAD_TEACHER_PHOTO_FAIL = 'UPLOAD_TEACHER_PHOTO_FAIL';

export const VIEW_TEACHER_PHOTO_REQUEST = 'VIEW_TEACHER_PHOTO_REQUEST ';
export const VIEW_TEACHER_PHOTO_SUCCESS = 'VIEW_TEACHER_PHOTO_SUCCESS';
export const VIEW_TEACHER_PHOTO_FAIL = 'VIEW_TEACHER_PHOTO_FAIL';

