export const PROFILE_FORM_REQUEST = 'PROFILE_FORM_REQUEST ';
export const PROFILE_FORM_SUCCESS = 'PROFILE_FORM_SUCCESS';
export const PROFILE_FORM_FAIL = 'PROFILE_FORM_FAIL';

export const VIEW_PROFILE_REQUEST = 'VIEW_PROFILE_REQUEST';
export const VIEW_PROFILE_SUCCESS = 'VIEW_PROFILE_SUCCESS';
export const VIEW_PROFILE_FAIL = 'VIEW_PROFILE_FAIL';

export const CREATE_AGENCY_PROFILE_REQUEST = 'CREATE_AGENCY_PROFILE_REQUEST ';
export const CREATE_AGENCY_PROFILE_SUCCESS = 'CREATE_AGENCY_PROFILE_SUCCESS';
export const CREATE_AGENCY_PROFILE_FAIL = 'CREATE_AGENCY_PROFILE_FAIL';

export const RESET_PROFILE = 'RESET_PROFILE';