export const UPLOAD_TEACHER_VIDEO_REQUEST = 'UPLOAD_TEACHER_VIDEO_REQUEST ';
export const UPLOAD_TEACHER_VIDEO_SUCCESS = 'UPLOAD_TEACHER_VIDEO_SUCCESS';
export const UPLOAD_TEACHER_VIDEO_FAIL = 'UPLOAD_TEACHER_VIDEO_FAIL';

export const VIEW_TEACHER_VIDEO_REQUEST = 'VIEW_TEACHER_VIDEO_REQUEST ';
export const VIEW_TEACHER_VIDEO_SUCCESS = 'VIEW_TEACHER_VIDEO_SUCCESS';
export const VIEW_TEACHER_VIDEO_FAIL = 'VIEW_TEACHER_VIDEO_FAIL';

